name: Client

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Build and Push Image ]
    types: [ completed ]
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      openapi: ${{ steps.changes.outputs.openapi }}
    steps:
      - uses: actions/checkout@v2
      - name: File changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          filters: |
            openapi:
                - iam_openapi_spec.yml

  java-client:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.openapi == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: iam
          ssh-key: ${{ secrets.GIT_CLONE_SSH_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: togaihq/iam-java-client
          path: client
          ssh-key: ${{ secrets.GIT_CLONE_SSH_KEY }}
          persist-credentials: true
          fetch-depth: 0
      - name: Move the spec file
        run: |
          mv iam/iam_openapi_spec.yml client/iam_openapi_spec.yml
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate Files
        working-directory: client
        run: |
          gradle --stacktrace --debug generateClient
      - name: Push changes to iam-java-client
        shell: bash
        run: |
          cd client
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update OpenApi spec"
          git push origin main
